Add JUnit config to intellijinit
graalvm/mx pull request #133
Opened 2017-04-26 12:55 UTC by pejovica

Makes intellijinit generate default run/debug configuration for JUnit.

There are two aspects to proposed changes. First one is the placement of generated configuration. At the moment it is stored in the workspace.xml, since the official location is not available yet (IDEA-65915). And the second one is the collection of necessary VM parameters for JUnit to run. I tried to reuse mx unittest for that by effectively making it execute a dry run. This implementation of dry run only prevents tests from running. It doesn't prevent side effects, e.g., unittest's test discovery and caching. But since unittest allows custom launchers, i.e., implemented by other modules, I am not sure what can be expected from them in this regard. Graal core seems to work fine.

2017-04-26 14:40 UTC, vjovanov commented
@pejovica could you please sign the oracle contributor agreement? Here are the instructions: 
  http://www.oracle.com/technetwork/community/oca-486395.html
Also, the gate is failing due to style issues. To reproduce locally run: 
```
mx --strict-compliance gate --strict-mode
```

2017-04-26 17:00 UTC, vjovanov commented
Otherwise, LGTM

2017-05-26 10:35 UTC, pejovica commented
I've added the final set of changes, so could you have another look?

2017-06-01 08:21 UTC, vjovanov requested changes

2018-11-28 08:53 UTC, vjovanov commented
@pejovica will there be progress on this or we can close the PR?

2021-12-14 11:15 UTC, vjovanov commented
@pejovica is this still valid?

2026-07-07 15:57 UTC, closed without merging